# Generated by Django 5.2.9 on 2026-01-18 03:23

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('delegacion', 'Delegación'), ('farmacia', 'Farmacia'), ('optica', 'Óptica'), ('otro', 'Otro'), ('exterior', 'Exterior'), ('interior', 'Interior')], max_length=30)),
                ('duration', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('description', models.TextField(blank=True, help_text='Descripción del trabajo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('before_after', models.CharField(choices=[('before', 'Antes'), ('after', 'Después')], max_length=6)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Foto de Trabajo',
                'verbose_name_plural': 'Fotos de Trabajos',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.tag'),
        ),
    ]
