# Generated by Django 5.2.9 on 2025-12-03 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('delegacion', 'Delegación'), ('farmacia', 'Farmacia'), ('optica', 'Óptica'), ('otro', 'Otro')], max_length=30)),
                ('duration', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('description', models.TextField(blank=True, help_text='Descripción del trabajo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='jobs/%Y/%m/%d/')),
                ('before_after', models.CharField(choices=[('before', 'Antes'), ('after', 'Después')], max_length=6)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.job')),
            ],
        ),
    ]
