# Generated by Django 5.2.9 on 2025-12-08 02:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobphoto',
            options={'verbose_name': 'Foto de Trabajo', 'verbose_name_plural': 'Fotos de Trabajos'},
        ),
        migrations.AlterField(
            model_name='jobphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
